### ISSUE TITLE
Feature Request: Toggle GameObject[] instead of GameObject

### ISSUE THREAD

**Issue by YukihoAA** [hai-vr/Just1Int7Toggles#1]
Thank you for making great script for Avatar 3.0
I tried this script today and it is very convenient to make closet feature. 

I have some idea to improve this script.

At this moment, J1I7T can toggle single game object with single Toggle action but I think it will be great if I can toggle multiple object with 1 toggle action. 

ex)

Now>
Item #1
Item(J1I7T_A_0) [GameObject]
Default state      [v]

To>
Slot #1 (J1I7T_A_0)
Size           [Int]
Item[1]      [GameObject]
Item[2]      [GameObject]
...
Item[size]  [GameObject]

(adptive UI, like dynamic bone collider setting)

**Comment by hai-vr** [comment]
I will publish a pre-release V0.2.0 will on GItHub as I have not yet properly tried this new feature.

I have also added an option to inverse toggle per-child item (object swapping).

![image](https://user-images.githubusercontent.com/60819407/90346046-0ece4680-e026-11ea-8860-525d113e7c7c.png)

**Comment by hai-vr** [comment]
Hello @YukihoAA ,

Thank you for your feedback 😃

Could you please download the pre-release at https://github.com/hai-vr/Just1Int7Toggles/releases/tag/V0.2.0rc1 and see if it suits you?

Regards,

**Comment by YukihoAA** [comment]
@hai-vr Works fine to me, could toggle 2 Items in single Toggle menu. Thank you for fast reply :)
